### ISSUE TITLE
Heroku not free anymore

### ISSUE THREAD

**Issue by dearvoodoo** [dearvoodoo/Hunt-Showdown-API#1]
Heroku is not free anymore.
When I have time to move this on this API I will search for a new hosting plateform. 
If you know some free hosting node service please comment. ♥

VooDoo

**Comment by thiagopeluque** [comment]
Hi! I was looking for it too and found this one
https://render.com/

I don't know if it helps you but it's already something and I would like you to continue with the project and if you need anything I'm happy to help

**Comment by thiagopeluque** [comment]
> Hi! I was looking for it too and found this one https://render.com/
> 
> I don't know if it helps you but it's already something and I would like you to continue with the project and if you need anything I'm happy to help

After answering I saw that you had already solved the problem :D. Sorry

**Comment by dearvoodoo** [comment]
Yup and now the API is moving on my server.
That way I have more control on what I can do :D
